### ISSUE TITLE
Security rules for private network

### ISSUE THREAD

**Issue by xadereq** [pgaxatte/openstack-workshops#5]
As you mentioned in [02c_security_groups](https://github.com/pgaxatte/openstack-workshops/blob/master/02_manage_resources_advanced/02c_security_groups.md)
> Defining security rules on the private network is not (yet) supported at OVH.

Is there any update on this? Some kind of deadline?

Kindly thank you for your information.

@pgaxatte

**Comment by pgaxatte** [comment]
Hello,

I believe this is on our roadmap, as part of https://github.com/ovh/public-cloud-roadmap/issues/40 but if you want a precise answer, you can create a new issue in https://github.com/ovh/public-cloud-roadmap
